(package "scroll-text"
         "0.1.1"
         "Scroll the text for content")

(website-url "https://github.com/jcs-elpa/scroll-text")
(keywords "scroll" "animation" "animate" "text")

(package-file "scroll-text.el")

(source "melpa")

(depends-on "emacs" "24.3")
(depends-on "dash")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
